name: Schedule 

on: 
  schedule: 
    - cron: "00 18 18 7 *"
  workflow_run:
    workflows: ["Learning Github actions"]
    types: 
      - completed

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Show a message
        run: echo "Hello world!"
      - name: Multiple commands
        run: |
          node -v
          npm -v